### ISSUE TITLE
pages next on "hostgroups Summary" is on left, and not center

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4438]
Hello,

Pages "1,2,3...> >>" are on left, and not on center of the page.

Thanks in advance.
![cap 2016-05-23 a 22 45 15](https://cloud.githubusercontent.com/assets/10330979/15484051/4378c1e6-2138-11e6-9faf-38ec09c5d963.png)

**Comment by julienmathis** [comment]
Should be fixed with the last commit

**Comment by querwin** [comment]
Still not OK
![hg-summary](https://cloud.githubusercontent.com/assets/7510531/16915484/04947dbc-4cf8-11e6-8f2c-b1ba2fe4351b.png)

**Comment by julienmathis** [comment]
Now it's ok !

**Comment by querwin** [comment]
Well done :)
