### ISSUE TITLE
Possibility to edit custom macros with blocked template

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4478]
On a host template blocked, Macros seems to be editable.
Morover, if a macros is a password, the box "password" is never checked
![2016-06-14_160204](https://cloud.githubusercontent.com/assets/3351916/16045587/5de4fe6a-3249-11e6-911b-6d4e242f9b10.png)

**Comment by Manu1400** [comment]
Fixed in 2.8.x (on all webpages)

**Comment by kduret** [comment]
Not fixed, revert by 3966977ed50ab291e398b2a6042d0105a6d8f0b0
