### ISSUE TITLE
Problem With Service Templates Page (Section of Page Missing)

### ISSUE THREAD

**Issue by ellingtonb** [centreon/centreon#4530]
I am having a problem when I click on the link menu **Configuration > Services > Templates**, where the section of the page that shows the content - table of all service templates and the option to add a new service template and see  details about - is empty/missing like the picture bellow.

![template_page](https://cloud.githubusercontent.com/assets/3523312/16769081/6f36b2a0-481d-11e6-998b-3abff0e55b4d.png)

When I click on the name of a template service in a host, the result is the same. The section of the page that shows the content of the related service template is empty/missing.

What could I do to solve this possible issue?
If you need more information related my server, please ask me.

I installed the Centreon by FAN Nagios.

Thanks

**Comment by ellingtonb** [comment]
The problem described above was solved while I was inserting new hosts and services, but I don't know what need to be done to solve this.
Anyway, thanks

**Comment by julienmathis** [comment]
Hello, 

Do you have errors in apache file ?

BR

**Comment by silentbobj** [comment]
Hi I have the same issue (not resolved), looking in the httpd error log the following is repeated over and over 

PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/class/centreonService.class.php on line 296

looking at the PHP file and the error it looks like an error when the page is trying to fetch the info from the DB
