### ISSUE TITLE
Set downtimes randomly work/don't work, remain in web interface after finish

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#4702]
Centreon Web version: 2.7.5-7
Centreon Engine version: 1.5.1-3
Centreon Broker version: 2.11.5-2
OS: CentOS 6.8 (CES 3.3 iso)
1. Using the web interface, in Monitoring, Downtimes, click on Add a host downtime button, select hostgroup, deselect Fixed, set duration to 8 hours, enter same duration using Start time/End time with a date in the future, Set downtime for hosts services: Yes, enter a short comment, Save.
2. (after clicking Search button to refresh page),  the downtimes show up with the correct start/end dates, 28800 seconds duration, Started: No, Fixed: No.
3. When the set timeperiod arrives, most services turn to Started: Yes, but some services seemingly randomly remain in Started: No. (there are even hosts with one or more services "Yes", and one "No")
4. In Status Details/Hosts view, all hosts in the hostgroup will show up in purple, but in Status Details/Services again some of the services will not show in purple and not have the purple triangle, as if no downtime for them had been set.
5. After the timeperiod elapses, some services remain in the web interface with the purple downtime icon and purple background until the downtimes are manually deleted in the Downtimes section. When selecting "Display Finished Downtime" in downtimes section, some services will have an "Actual End" entry, some continue to have "N/A".

**Comment by btassite** [comment]
Also, when mousing over elapsed downtime entries that still show up with the purple triangle for host/service entries in monitoring hosts/services view: the popup has no data, only the "Author  Fixed  Start Time  End Time  Comment".

This makes me think some select statement is looking at old centreon_storage database entries that happen to have the same key value as whatever it tries to select (i.e. multiple entries for the same host or service in the database because some value was changed and the old entry didn't get overwritten but copied).

**Comment by Hellnino18** [comment]
Hi,

I have the same problem in the branch Centreon 2.6.6

**Comment by kduret** [comment]
Hi,

I think you mix up **fixed** and **flexible** downtimes.
Here is the documentation about downtimes : https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/advanced/scheduled_downtime.html?highlight=downtime

Flexible downtimes are triggered only on down status on hosts and services.

Can you send us some screenshots ?
* red triangle with popup having no data
* "Never Started" items

I could not reproduce your problem on my side.

**Comment by Hellnino18** [comment]
Hi, for me in Centreon 2.6.6, this is an example of remaining downtime on host
![bug-downtime-centreon-2 6 6](https://cloud.githubusercontent.com/assets/14218330/18502790/9738fda8-7a59-11e6-90c5-5509183584ca.PNG)

**Comment by kduret** [comment]
It is fixed with Centreon-2.7.x
Here is the commit : 7073b739aff538adb879055aa13ddc0bd1fbc2f8

**Comment by Hellnino18** [comment]
thx @kduret for this problem of twice downtime. But why the red triangle is always present?

**Comment by btassite** [comment]
@kduret,

The problems remain the same regardless of fixed or flexible starttime, with flexible starttime it should just enter Started state later (when the host/service goes down instead of the downtime window start time), but _some services never enter Started state, at any time_.

Also, whether or not they entered Started state should not influence the removal of the downtime status after the maximum possible duration of End Time + duration elapses (or just End Time if fixed). If it's still there days after the downtime until the downtime entry is manually removed something is wrong.

Also the empty downtime popup window is still present in 2.7.5 (very much like Hellnino18's screenshot except in English), so the commit mentioned doesn't deal with my particular circumstances.

Lastly, if when manually deleting downtimes new entries appear out of nothing it's pretty certain something is wrong with the database or the routines selecting from it.

It would be nice if someone looked at the dependency/escalation issue I mentioned, since the above may be a consequence of some kind of db corruption caused by that and not be reproducible by others with a consistent database state.

**Comment by btassite** [comment]
BTW, I don't think this should matter, but the downtime was scheduled for a subnet change, so the Centreon config was changed inside the downtime window (host got new IP address).

Specific example of problems:

Hostgroup Z is scheduled for flexible downtime between 06:00-14:00 with a duration of 8 hours (28800 seconds)

Host X and Y are members of hostgroup Z.

X enters HARD-Down state at 06:54 at which point downtime should enter "Started" status (centreon_storage downtimes.actual_start_time translates to 06:00 for some reason)). Centreon config is changed at 10:08 with the new IP, host enters HARD-OK state at 10:10, services at various times after that according to their scheduling.

At 16:00 X is gone from downtimes unless selected with Display Finished Downtimes, then it and all its services show as "Started" but with Actual End "N/A" (downtimes.actual_end_time is NULL). Purple triangle/background are however not gone in monitoring view.

Y enters HARD-Down at 06:53, Centreon config changed for new IP at 10:09, Host HARD-OK status at 10:10. 

At 16:00 Y is gone from downtimes unless selected with Display Finished Downtimes, then the host shows as Started "Yes", Actual End 14:48 as well as one of its configured services. Of its 5 services the other 4 show as follows:
Started "Yes", End Time "14:00"
Started "Yes", End Time "14:48"
Started "Yes", End Time "N/A" (2x)
Started "No", End Time "N/A"

In services monitoring, the purple triangle is gone for everything that has an end time, but also for the service that has Started "No". The purple background and triangles remain for the 2 services that have Started "Yes", End Time "N/A". The db reflects the above (actual_start_time is NULL for the one with Started "No" etc.).

Another apparent bug: the perfdata for one of the service checks for host Y is stuck (uptime=39), even though its being checked every 2 hours and a manual check_nt returns the correct value (currently over 8 hours). This check is scheduled every 2 hours and never went into a critical state, just changed perfdata value at 11:06 (uptime=15). It's unclear why it now has a value 24 minutes higher, or why it hasn't been updated since. This is one of the services that has a Started "Yes" and End Time "N/A" (and remains purple/with triangle in service monitoring view).

**Comment by btassite** [comment]
Update: issued a forced check on the uptime service, it now reflects the correct value (but remains purple).

**Comment by btassite** [comment]
Next day: yesterday's scheduled downtimes that showed N/A still do, they're all still purple with triangle in monitoring services view, hovering over the triangles again shows only labels, no information. This is over 20 hours after their scheduled end times, or 12 hours after scheduled end time + the 8 hour duration.

Yesterday I added another hostgroup but this time with fixed scheduling for today, these all have a Started "Yes" status now and appear with purple background/triangles, so the above problems seem to be confined to non-fixed scheduling.

But another issue cropped up while rescheduling some downtimes (should I open a new bug for this?): when deleting downtimes, they aren't deleted but canceled. They all show up when selecting Display Finished Downtime as Cancelled "Yes". Only when using the delete option again there are they truly gone.

**Comment by btassite** [comment]
It occurred to me that the entries that reappeared after deleting them from downtimes may (partially?) be explained by the fact that they actually got cancelled instead of deleted and therefore reappear on a refresh with Display Finished Downtime selected, though that doesn't explain the discrepancy between the numbers (deleted maybe two dozen, 1, then 5 reappeared) or why this happened twice (after the second deletion no old entries should reappear unless some AJAX problem prevented the entry from being selected for deletion).

**Comment by lpinsivy** [comment]
Hi,

With Centreon 2.6.x and 2.7.x, punctual downtimes set by web UI are sent some time twice to Centreon Engine mostly if you refresh page (F5).

Moreover, a old bug send many time the same recurrent downtimes to Centreon Engine with same starttime and endtime. When you cancel the downtime from Centreon web UI, you cancel only the first but the others cloned downtimes still present (purple line with triangle).

Likewise, a bug included in Centreon Engine generate a wrong value in db for scheduled_downtime_depth field (hosts and services tables). The value can attempt -1 and that's why the Centreon web interface display a downtime with empty value.

All these mentioned problems are corrected in next release versions Centreon web 2.8.0, Centreon Engine 1.6.0 and Centreon Broker 3.0.0.

However, you describe a new bug using recurrent flexible downtimes on a hostgroup. Some time the downtime starttime if the datetime of NON-OK state, some time the starttime scheduled in downtimes. Moreover, the end time can’t by reach for some services without any reason. We will try to reproduce this issue.

Regards,
