### ISSUE TITLE
[Chart] zoom and displayed periods

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5112]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Steps to reproduce the issue:**
1. Go to "Monitoring > Performances  >  Graphs" menu
2. Select chart to display
3. Zoom on chart

**Describe the results you received:**

The start and end date dates are a little bit different with period display on chart

**Describe the results you expected:**

Same start and end dates

![screenshot at mars 29 13-52-22](https://cloud.githubusercontent.com/assets/3351916/24453174/1b4bb7ee-1487-11e7-9d0e-674a1fdd758c.png)

**Comment by kduret** [comment]
Fixed here : 65da8503013e031e9e6b556e8a2b663c8d8a63ca

**Comment by thiuyendang** [comment]
![image](https://user-images.githubusercontent.com/25612980/27912642-e948c21c-625d-11e7-9745-bd8d7edbebb1.png)

Still exists a small gap between period times and those displayed on X axis (time scale of the graph)
