### ISSUE TITLE
[2.8.6] non-admin user split chart permission

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5177]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.6-3

**Centreon Engine version**: 1.7.2-3

**Centreon Broker version**: 3.0.5

**OS**:  CentOS release 6.9 (Final) (CES VM)

**Steps to reproduce the issue:**
1. Monitoring  >  Performances  >  Graphs
2. Select a Graph
3. Click **Display multiple periods**
4. Try to export CSV or RRD PNG

**Describe the results you received:**

`Uncaught TypeError: Cannot read property 'match' of undefined
    at HTMLAnchorElement.<anonymous> (main.php?p=2040102&chartId=*****&start=*********&end=********:500)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.i (jquery.min.js:3)`

![image](https://cloud.githubusercontent.com/assets/25208457/25400947/98cbd11a-29ca-11e7-9129-d224f1f0e870.png)

**Comment by leo29041982** [comment]
Can confirm it with 2.8.6 (not tested with 2.8.5)

**Comment by kozfelipe** [comment]
Also, non-admin users dont have permission to split charts. I couldnt find any action access related.

**Comment by kozfelipe** [comment]
[#5171](5171) fix PNG issue, although permission for non-admin users remains

**Comment by kduret** [comment]
Works for me.

Probably fixed here : 
981e755d20cd6a3ac0e65986c996aaa588ce0f3a
3e25ef7352845644ca20ef7740f0e18fec63aaec

**Comment by kozfelipe** [comment]
> Works for me on 2.8.x branch.
>
>Probably fixed here :
>981e755
>3e25ef7

@kduret I appritiate the javascript fix, though the permission issue remains. Only admin user is allowed to split charts.

**Comment by kduret** [comment]
Hi,

You need to upgrade your menu access ACL cause chart splitting is a new page ;)

![image](https://cloud.githubusercontent.com/assets/11978823/26581682/148dadee-453e-11e7-8ca1-4ab36ba490e8.png)

**Comment by thiuyendang** [comment]
OK  after ACL fixing in 2.8.9-7

**Comment by thiuyendang** [comment]
Remove Split Chart and Display multiple periods buttons if user is not authorized to access to the related pages.

**Comment by thiuyendang** [comment]
OK 2.8.9-8
