### ISSUE TITLE
[2.7.8] Event Logs page doesn't show service by hostgroups

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#5185]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.8

**OS**: Centreon 3.4 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualized

**Steps to reproduce the issue:**
1. Go to event logs page 
2. Search for service by hostgroup in the drop down lists
3.

**Describe the results you received:**
I can't find any of my service by hostgroups 

**Describe the results you expected:**
Be able to select service of any kind in this page

**Additional information you think important :**
Seems like prelly similar to https://github.com/centreon/centreon/issues/4731 
Has been spotted and fixed prelly long time ago https://github.com/centreon/centreon/issues/1247

**Comment by lpinsivy** [comment]
Corrected on Centreon 2.8.x version.

fixed by commit 1a3b3a4 91585fe 29f2d54 bb2c293

**Comment by sbraz** [comment]
@lpinsivy I still have the problem with 2.8.14, can you re-open the issue? I enabled MySQL logs and this is the request that is executed:
```sql
SELECT SQL_CALC_FOUND_ROWS DISTINCT fullname,
                                    service_id,
                                    host_id
FROM (
        (SELECT DISTINCT CONCAT(h.host_name, " - ", s.service_description) as fullname,
                         s.service_id,
                         h.host_id
         FROM host h,
                   service s,
                   host_service_relation hsr
         WHERE hsr.host_host_id = h.host_id
           AND hsr.service_service_id = s.service_id
           AND h.host_register = "1"
           AND s.service_register = "1"
           AND CONCAT(h.host_name, " - ", s.service_description) LIKE '%%' )
      UNION ALL
        (SELECT DISTINCT CONCAT("Meta - ", ms.display_name) as fullname,
                         ms.service_id,
                         mh.host_id
         FROM host mh,
                   service ms
         WHERE mh.host_name = "_Module_Meta"
           AND mh.host_register = "2"
           AND ms.service_register = "2"
           AND CONCAT("Meta - ", ms.display_name) LIKE '%%' )) as t_union
ORDER BY fullname
LIMIT 0,
      60
```
It doesn't even reference `hostgroup_hg_id` so I think something is still missing.
