### ISSUE TITLE
[2.8.7] Special characters in Meta-services

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5204]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.7

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.5

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Create a meta-service with an output which contains a special character (see attached picture)
2. Generate the configuration
3. Go to Monitoring ==> Meta Hosts

**Describe the results you received:**
Special characters is not correctly displayed (see attached picture)

**Describe the results you expected:**
Special characters should be correctly displayed
<img width="526" alt="monitoring_meta" src="https://cloud.githubusercontent.com/assets/2960490/25770938/3a90108a-3243-11e7-945c-44eaad78b44d.PNG">
<img width="393" alt="configuration_meta" src="https://cloud.githubusercontent.com/assets/2960490/25770940/4d7807d4-3243-11e7-9eed-9c7ba69e5727.PNG">

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by zskarman** [comment]
Hi,

We had the similar issue, when we saved the macros or args with space.
Solution was $data = html_entity_decode($data);

But you need to know where that page php's file function, where is the save process..

Rgs, Zsolt

**Comment by kduret** [comment]
Fixed here : 3df02c6aa38afdbc8f30e517df89ef6ef6f6833c

**Comment by thiuyendang** [comment]
Still not OK in 2.8.9-6

![metaservice_quote](https://cloud.githubusercontent.com/assets/25612980/26545266/45f6fdce-4465-11e7-8eab-1c0efc2abad8.png)

**Comment by thiuyendang** [comment]
Still not OK in 2.8.9-13

**Comment by thiuyendang** [comment]
Configuration metaservice page OK : 

![to_hide](https://cloud.githubusercontent.com/assets/25612980/26732907/857ad446-47b9-11e7-9bb1-7d3a4fe1c39b.png)

Monitoring Status details Services KO 

![image](https://cloud.githubusercontent.com/assets/25612980/26732990/c9822dce-47b9-11e7-8cec-2ff24ecf30b5.png)

**Comment by lpinsivy** [comment]
Problem is from Centreon Meta Service Plugin and not web interface:

# /usr/lib/centreon/plugins/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=metaservice --centreon-config=/etc/centreon/conf.pm --meta-id 8
CRITICAL: Moyenne d&#039;utilsation  RTA : 0.09 ms | 'g[value]'=0.09;0:0.05;0:0.09;;

**Comment by lpinsivy** [comment]
@garnier-quentin can you check that?
