### ISSUE TITLE
Graph are not correctly scaled

### ISSUE THREAD

**Issue by GallandJe** [centreon/centreon#5248]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.8

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS release 6.9 (Centreon Entreprise Server)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware virtual machine

**Steps to reproduce the issue:**
1. Create a command who check the trafic of a host ($USER1$/check_centreon_snmp_traffic -H $HOSTADDRESS$ -i $ARG1$)
2. Create a new graph for show the trafic of the host you want to oversee
3. You can see this bug : 
![image](https://cloud.githubusercontent.com/assets/12172206/26189112/2bebf620-3ba3-11e7-83d9-3f68fde6d247.png)

As you can see, the graph is not correctly scaled.. and i have two dead links for the images at the bottom of the graph. I made all the updates but that didn't works :( 

Thanks for your help !

**Comment by kduret** [comment]
Fixed here : 3e25ef7352845644ca20ef7740f0e18fec63aaec

**Comment by thiuyendang** [comment]
OK 2.8.9

ex : 
![traffic 2_8_9](https://cloud.githubusercontent.com/assets/25612980/26552302/dc468fb2-4486-11e7-8e4d-9db1f6495573.png)

**Comment by thiuyendang** [comment]
OK 2.8.9 for traffic_in unit

**Comment by thiuyendang** [comment]
Check extra legend for traffic in : negative values, not rounded

**Comment by thiuyendang** [comment]
![trafficin_extralegend](https://cloud.githubusercontent.com/assets/25612980/26640945/762f7460-4629-11e7-997b-11ee42d11c7c.png)

**Comment by thiuyendang** [comment]
Fixed in 2.8.9-12

**Comment by GallandJe** [comment]
Hello,
There's still a problem with the graphs... I can see the traffic out of my switch but the traffic in is not showed like you can see here : 
![image](https://user-images.githubusercontent.com/12172206/27536635-58382db6-5a70-11e7-8f12-5f808ab625ed.png)

**Comment by thiuyendang** [comment]
Hello, 
which graph-monitoring release do you use ?
The fix is available in version 1.5.2 of centreon-widget-graph-monitoring.noarch file.

**Comment by GallandJe** [comment]
I updated to version 1.5.2 but the problem is persisting

**Comment by kduret** [comment]
Hi,

I think you have a problem in your graph template configuration.

Please go to "Monitoring > Performances > Templates" and edit "Default_Graph".
Then, you have to let field "Lower Limit" to empty.

**Comment by GallandJe** [comment]
Hi @kduret 

Yes, that's it ! it's working now, thanks :)
