### ISSUE TITLE
[2.8.8] Graph drawing is not working well

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5351]
**Centreon Web version**:2.8.8
**Centreon Engine version**:1.7.2
**Centreon Broker versio**n:3.0.7
**OS**: Oracle Linux 7
**Additional environment details** :Virtual
**Steps to reproduce the issue**:

Graph Drawing is not working. We are using rrdcached as well. We have about 200 thousand checks in Centreon now. Maybe we  reached a limitation and the broker cannot handle this load? 

**Describe the results you received:**
We are getting many errors like this in rrdcached and central-rrd log as well.

Jun 15 09:32:44 Server01 rrdcached[28179]: queue_thread_main: rrd_update_r (/var/lib/centreon/metrics/1557121.rrd) failed with status -1. (/var/lib/centreon/metrics/1557121.rrd: illegal attempt to update using time 1497530554 when last update time is 1497530554 (minimum one second step))
Jun 15 09:32:44 Server01  rrdcached[28179]: queue_thread_main: rrd_update_r (/var/lib/centreon/metrics/1557237.rrd) failed with status -1. (/var/lib/centreon/metrics/1557237.rrd: illegal attempt to update using time 1497530554 when last update time is 1497530554 (minimum one second step))
Jun 15 09:32:44 Server01  rrdcached[28179]: queue_thread_main: rrd_update_r (/var/lib/centreon/metrics/1557237.rrd) failed with status -1. (/var/lib/centreon/metrics/1557237.rrd: illegal attempt to update using time 1497530554 when last update time is 1497530554 (minimum one second step))
Jun 15 09:33:49 Server01  rrdcached[28179]: queue_thread_main: rrd_update_r (/var/lib/c
![ticket-1](https://user-images.githubusercontent.com/25457811/27187616-f591e59e-51eb-11e7-999e-dada8d116edd.PNG)
![ticket-2](https://user-images.githubusercontent.com/25457811/27187636-fe7aea84-51eb-11e7-9825-eba6ed0de9b2.PNG)

**Describe the results you expected:**
We expect that graph drawing should working.

**Comment by zskarman** [comment]
Guys,

Could you please have a look at, it's an bit urgent for us.

Thank you for your help.

Regards, Zsolt

**Comment by julienmathis** [comment]
Hello, 

Centreon Broker works with 200 000 checks. The only one problem that I can see is that Broker is currently trying to update the RRDTool DB with an older value that the last update. 

All graphs are empty ? 
Do you do something specific ? upgrade / restart / reboot ? 
Do you encounter a specific problem ? Full filesystem, crash or other ? 

Thanks in advance,

**Comment by Tomszy** [comment]
Yes Graphs were empty. We fixed the problem that we truncated the metrics table but this is not the good solution. We also restarted cbd etc. But it did  not help.
How can we fix the older value that the last update issue? 
We checked the system time and it was ok on engine and the pollers as well.
And also we can see this errors now:

Jun 15 09:32:44 Server01 rrdcached[28179]: queue_thread_main: rrd_update_r (/var/lib/centreon/metrics/1557121.rrd) failed with status -1. (/var/lib/centreon/metrics/1557121.rrd: illegal attempt to update using time 1497530554 when last update time is 1497530554 (minimum one second step))

We didnt find any plus switch in rrdcached configuration which can resolve it.

Thanks,

Tamas

**Comment by zskarman** [comment]
Hi,

We still get this error, could we refresh this topic?
![image](https://user-images.githubusercontent.com/24320218/30786580-663451fc-a178-11e7-9643-f84f3e2f8931.png)

Regards, Zsolt

**Comment by Tomszy** [comment]
We have the same issue now. Any update regarding this issue?

**Comment by lpinsivy** [comment]
you can modify default values to reduce queue: "-w 3600 -z 3600 -f 7200"
