### ISSUE TITLE
Adding remote poller CentOS 7 not working

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#5677]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.12

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.9

**OS**: CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Adding poller following the offical procedure
2.
3.

**Describe the results you received:**

Poller not "detected" in poller tab (master) and monitoring data not sent to the central
SSH key is OK for user "centreon"

**Describe the results you expected:**
...

**Additional information you think important (e.g. issue happens only occasionally):**

Logs on poller :
centengine[11900]: segfault at 34 ip 00007fbe2dfcd4d8 sp 00007ffe8282f450 error 4 in cbmod.so[7fbe2de8d000+1c3000

Also :
==> /var/log/centreon/centcore.log <==
2017-09-14 15:42:05 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-09-14 15:42:05 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-09-14 15:42:05 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-09-14 15:42:05 - Error when getting server properties

However password is OK

**Comment by lpinsivy** [comment]
Hi,

What is your version of CentOS?

For the second error, you need to generate Centreon SNMP traps database from "Configuration  >  SNMP Traps  >  Generate" menu?

**Comment by gslongo** [comment]
Hi,

I'm on the latest version  : CentOS Linux release 7.4.1708 (Core) 

I will test regarding traps this afternoon

Thanks

**Comment by gslongo** [comment]
Hi

Any news regarding this ?

Thanks

**Comment by gslongo** [comment]
For information, generating traps does not change anything

**Comment by lpinsivy** [comment]
Should be corrected with:

- Centreon Engine 1.8.1 & Centreon Broker 3.0.11

**Comment by gslongo** [comment]
Hi,

Issue still present :

[root@poller1 ~]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 

[root@poller1 ~]# rpm -qa | grep centreon
centreon-engine-daemon-1.8.1-1.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20170807-1.el7.noarch
centreon-connector-perl-1.1.3-1.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20170808-1.el7.noarch
centreon-broker-storage-3.0.11-1.el7.centos.x86_64
centreon-plugins-2.8.16-8.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20170807-1.el7.noarch
centreon-plugin-Applications-Protocol-Ldap-20170807-1.el7.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20170807-1.el7.noarch
centreon-engine-1.8.1-1.el7.centos.x86_64
centreon-plugin-meta-2.8.16-8.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20170807-1.el7.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20170807-1.el7.noarch
centreon-common-2.8.16-8.el7.centos.noarch
centreon-perl-libs-2.8.16-8.el7.centos.noarch
centreon-broker-cbmod-3.0.11-1.el7.centos.x86_64
centreon-web-2.8.16-8.el7.centos.noarch
centreon-broker-cbd-3.0.11-1.el7.centos.x86_64
centreon-clib-1.4.2-3.el7.centos.x86_64
centreon-connector-1.1.3-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Http-20170807-1.el7.noarch
centreon-plugin-Applications-Protocol-Ftp-20170807-1.el7.noarch
centreon-poller-display-1.6.0-2.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20170807-1.el7.noarch
centreon-broker-3.0.11-1.el7.centos.x86_64
centreon-trap-2.8.16-8.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20170807-1.el7.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20170807-1.el7.noarch
centreon-engine-extcommands-1.8.1-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20170807-1.el7.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20170807-1.el7.noarch
centreon-release-3.4-4.el7.centos.noarch
centreon-broker-core-3.0.11-1.el7.centos.x86_64
centreon-poller-centreon-engine-2.8.16-8.el7.centos.noarch
centreon-connector-ssh-1.1.3-1.el7.centos.x86_64


===========================================================================================


==> /var/log/centreon-broker/poller-module.log <==
Centreon Broker 3.0.11 log file opened
[1511857383] error:   main: cbmod loading failed: BBDO: category 2 is already registered whereas it should be reserved for the BBDO core
Centreon Broker 3.0.11 log file closed

==> /var/log/centreon-engine/centengine.log <==
[1511857383] [1530] Centreon Engine 1.8.1 starting ... (PID=1530)
[1511857383] [1530] Local time is Tue Nov 28 09:23:03 2017
[1511857383] [1530] LOG VERSION: 2.0
[1511857383] [1530] Centreon Broker: log applier: applying 1 logging objects
[1511857383] [1530] Event broker module '/usr/lib64/nagios/cbmod.so' initialized successfully

==> /var/log/messages <==
Nov 28 09:23:03 poller1 systemd: Started Centreon Engine.
Nov 28 09:23:03 poller1 systemd: Starting Centreon Engine...
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Reading main configuration file '/etc/centreon-engine/centengine.cfg'.
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/hostTemplates.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/hosts.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/serviceTemplates.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/services.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/commands.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/contactgroups.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/contacts.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/hostgroups.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/servicegroups.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/timeperiods.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/escalations.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/dependencies.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/connectors.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/meta_host.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Processing object config file '/etc/centreon-engine/meta_services.cfg'
Nov 28 09:23:03 poller1 centengine: [1511857383] [1530] Reading resource file '/etc/centreon-engine/resource.cfg'
Nov 28 09:23:03 poller1 centreon-engine: [1511857383] [1530] Centreon Engine 1.8.1 starting ... (PID=1530)
Nov 28 09:23:03 poller1 centreon-engine: [1511857383] [1530] Local time is Tue Nov 28 09:23:03 2017#012LOG VERSION: 2.0
Nov 28 09:23:03 poller1 systemd-logind: Removed session 6.
Nov 28 09:23:03 poller1 systemd: Removed slice User Slice of centreon.
Nov 28 09:23:03 poller1 systemd: Stopping User Slice of centreon.
Nov 28 09:23:03 poller1 centreon-engine: [1511857383] [1530] Event broker module '/usr/lib64/nagios/cbmod.so' initialized successfully
**Nov 28 09:23:03 poller1 kernel: centengine[1530]: segfault at 34 ip 00007fa5b66b3648 sp 00007ffd080189f0 error 4 in cbmod.so[7fa5b6572000+1c4000]**
Nov 28 09:23:03 poller1 systemd: centengine.service: main process exited, code=killed, status=11/SEGV
Nov 28 09:23:03 poller1 systemd: Unit centengine.service entered failed state.
Nov 28 09:23:03 poller1 systemd: centengine.service failed.
Nov 28 09:23:04 poller1 systemd: Removed slice User Slice of apache.
Nov 28 09:23:04 poller1 systemd: Stopping User Slice of apache.


Can you help ?

**Comment by Alvaroctal** [comment]
Having kind of the same trouble here:

**OS**: CentOS 7.4 (AARCH64) [remote poller]
**centreon-engine**: 1.8.1
**centreon-broker**: 3.0.12
as far as I know both should be running at the poller, but when I restart the `centengine`, `/var/log/centreon-broker/module.log` shows (BTW, no errors are logged when `cbd` is restarted (in fact netstat at the server shows income packages)):
```
Centreon Broker 2.12.0 log file opened
config:  log applier: applying 1 logging objects
[1514114983] [0x36db29f0] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/05-dumper.so': Cannot load library /usr/share/centreon/lib/centreon-broker/05-dumper.so: (/usr/share/centreon/lib/centreon-broker/05-dumper.so: undefined symbol: _ZTIN3com8centreon6broker7mapping6sourceE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/10-neb.so': Cannot load library /usr/share/centreon/lib/centreon-broker/10-neb.so: (/usr/share/centreon/lib/centreon-broker/10-neb.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/15-stats.so': Cannot load library /usr/share/centreon/lib/centreon-broker/15-stats.so: (/usr/share/centreon/lib/centreon-broker/15-stats.so: undefined symbol: _ZN3com8centreon6broker6config7applier8endpoint13endpoints_endEv)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/20-bam.so': Cannot load library /usr/share/centreon/lib/centreon-broker/20-bam.so: (/usr/share/centreon/lib/centreon-broker/20-bam.so: undefined symbol: _ZTIN3com8centreon6broker7mapping6sourceE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/20-storage.so': Cannot load library /usr/share/centreon/lib/centreon-broker/20-storage.so: (/usr/share/centreon/lib/centreon-broker/20-storage.so: undefined symbol: _ZThn1056_NK3com8centreon6broker10exceptions3msg4whatEv)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/30-correlation.so': Cannot load library /usr/share/centreon/lib/centreon-broker/30-correlation.so: (/usr/share/centreon/lib/centreon-broker/30-correlation.so: undefined symbol: _ZTIN3com8centreon6broker7mapping6sourceE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/40-notification.so': Cannot load library /usr/share/centreon/lib/centreon-broker/40-notification.so: (/usr/share/centreon/lib/centreon-broker/40-notification.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/50-tcp.so': Cannot load library /usr/share/centreon/lib/centreon-broker/50-tcp.so: (/usr/share/centreon/lib/centreon-broker/50-tcp.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/60-tls.so': Cannot load library /usr/share/centreon/lib/centreon-broker/60-tls.so: (/usr/share/centreon/lib/centreon-broker/60-tls.so: undefined symbol: _ZN3com8centreon6broker2io6stream5flushEv)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/70-graphite.so': Cannot load library /usr/share/centreon/lib/centreon-broker/70-graphite.so: (/usr/share/centreon/lib/centreon-broker/70-graphite.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/70-influxdb.so': Cannot load library /usr/share/centreon/lib/centreon-broker/70-influxdb.so: (/usr/share/centreon/lib/centreon-broker/70-influxdb.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/70-rrd.so': Cannot load library /usr/share/centreon/lib/centreon-broker/70-rrd.so: (/usr/share/centreon/lib/centreon-broker/70-rrd.so: undefined symbol: _ZThn1056_NK3com8centreon6broker10exceptions3msg4whatEv)
[1514114983] [0x36db29f0] error:   modules: could not load library '/usr/share/centreon/lib/centreon-broker/80-sql.so': Cannot load library /usr/share/centreon/lib/centreon-broker/80-sql.so: (/usr/share/centreon/lib/centreon-broker/80-sql.so: undefined symbol: _ZNK3com8centreon6broker2io7factory16has_not_endpointERNS1_6config8endpointE)
[1514114983] [0x36db29f0] config:  endpoint applier: no matching protocol found for endpoint 'module-output-failover'
```

but `/var/log/centreon-engine/centengine.log` seems to run fine:
```
[1514115209] [1759] Caught SIGTERM, shutting down ...
[1514115209] [1759] Successfully shutdown ... (PID=1759)
[1514115209] [1759] Event broker module '/usr/lib/centreon-engine/externalcmd.so' deinitialized successfully
[1514115209] [1759] Event broker module '/usr/lib/centreon-broker/cbmod.so' deinitialized successfully
[1514115211] [1844] Centreon Engine 1.8.1 starting ... (PID=1844)
[1514115211] [1844] Local time is Sun Dec 24 12:33:31 2017
[1514115211] [1844] LOG VERSION: 2.0
[1514115211] [1844] Event broker module '/usr/lib/centreon-engine/externalcmd.so' initialized successfully
[1514115211] [1844] Centreon Broker: log applier: applying 1 logging objects
[1514115211] [1844] Event broker module '/usr/lib/centreon-broker/cbmod.so' initialized successfully
[1514115211] [1844] INITIAL HOST STATE: google.com;DOWN;HARD;3;(No output returned from host check)
[1514115211] [1844] INITIAL HOST STATE: satelite-00001;UP;HARD;1;OK
[1514115211] [1844] INITIAL SERVICE STATE: google.com;ping;CRITICAL;HARD;3;(No output returned from plugin)
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;cpu;OK;HARD;1;CPU OK : idle 100.00%
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;disk_activity;OK;HARD;1;DISK IO OK
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;disk_usage;OK;HARD;1;DISK OK used :  / 42.37% free
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;load;OK;HARD;1;LOAD AVERAGE OK : 0.00,0.00,0.00
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;memory;OK;HARD;1;MEMORY OK : Mem used: 49.28%, Swap used: 0.52%
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;network;OK;HARD;1;NET USAGE OK eth0:1.12KB
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;ping;CRITICAL;HARD;5;(No output returned from plugin)
[1514115211] [1844] INITIAL SERVICE STATE: satelite-00001;uptime;OK;HARD;1;OK : up 0 days, 18:01:16
[1514115212] [1844] Event loop start at Sun Dec 24 12:33:32 2017
[1514115212] [1844] Configuration loaded, main loop starting.
```

Here you have my module.xml:
```
<centreonBroker>
 <broker_id><![CDATA[4]]></broker_id>
 <broker_name><![CDATA[satelite-00001-module]]></broker_name>
 <poller_id><![CDATA[2]]></poller_id>
 <poller_name><![CDATA[satelite-00001]]></poller_name>
 <module_directory><![CDATA[/usr/share/centreon/lib/centreon-broker]]></module_directory>
 <log_timestamp><![CDATA[1]]></log_timestamp>
 <log_thread_id><![CDATA[1]]></log_thread_id>
 <event_queue_max_size><![CDATA[100000]]></event_queue_max_size>
 <command_file><![CDATA[]]></command_file>
 <cache_directory><![CDATA[/var/lib/centreon-broker/]]></cache_directory>
 <logger>
  <name><![CDATA[/var/log/centreon-broker/module.log]]></name>
  <config><![CDATA[yes]]></config>
  <debug><![CDATA[no]]></debug>
  <error><![CDATA[yes]]></error>
  <info><![CDATA[no]]></info>
  <level><![CDATA[low]]></level>
  <type><![CDATA[file]]></type>
 </logger>
 <output>
  <name><![CDATA[module-output]]></name>
  <port><![CDATA[5669]]></port>
  <host><![CDATA[monitor.my-domain.com]]></host>
  <failover><![CDATA[module-output-failover]]></failover>
  <retry_interval><![CDATA[60]]></retry_interval>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <protocol><![CDATA[bbdo]]></protocol>
  <tls><![CDATA[no]]></tls>
  <negotiation><![CDATA[yes]]></negotiation>
  <one_peer_retention_mode><![CDATA[no]]></one_peer_retention_mode>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[ipv4]]></type>
 </output>
 <output>
  <name><![CDATA[module-output-failover]]></name>
  <path><![CDATA[/lib/centreon-engine/module-output.retention]]></path>
  <protocol><![CDATA[bbdo]]></protocol>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[file]]></type>
 </output>
 <stats>
  <type><![CDATA[stats]]></type>
  <name><![CDATA[satelite-00001-module-stats]]></name>
  <json_fifo><![CDATA[/var/lib/centreon-broker//satelite-00001-module-stats.json]]></json_fifo>
 </stats>
</centreonBroker>
```

**Comment by physicalit** [comment]
After reading this issue, I think the same with mine. 
Actually the poller works, but in the web interface is see it like is down, but i have moved checks on the new poller and verified the logs of the poller and everything is ok. Only in the web interface is not possible to see if the poller is working correctly.

**Comment by Stanley974** [comment]
I'm having the same problème as @physicalit. Is there any news about this issue ? Thank you

**Comment by Stanley974** [comment]
I'm having the same issue as @physicalit. Is there any news about this issue ? Thank you
