### ISSUE TITLE
Problem Reload Service Filter

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#7306]
<h1>Problem Reload Service Filter </h1>

***Version 2.8.27***

When you change filter "Status service" in Supervision -> Status Details, the page dosen't refresh. You need to wait refresh time to see the status of service

**Comment by ptitpopey** [comment]
This problem appear only 2.8.27 version. I have downgrade to 2.8.26 and the problem disapear.

**Comment by CPbN** [comment]
Same issue here.

Go to Monitoring / Services.
Service status is by default set to "Unhandled Problems".
Set it to All.

It will automatically update 15 seconds later, but not immediately.
If you want to update it immediately, you have to toggle it to another value first...

**Comment by CPbN** [comment]
Same issue here.

Go to Monitoring / Services.
Service status is by default set to "Unhandled Problems".
Set it to "All".

It will automatically update 15 seconds later, but not immediately.
If you want to update it immediately, you have to toggle it to another value first...

Edit : issue still present in 19.04.0.

**Comment by BenoitPoulet** [comment]
Hello,

We upgrade to 2.8.27, and same pb.

This is really painful, many users are complaining about this. Please provide a fix.

**Comment by CPbN** [comment]
Culprits are here @callapa :) :
(2.8.x) https://github.com/centreon/centreon/commit/f41e5408e4eb8ddcfa376808574b90b4e850a860
(18.10.2+) https://github.com/centreon/centreon/commit/1bf7ff5276bc1415d4e8eb8762bf555554d9bf0f

Where the following has been removed from `service.php` :
```
window.clearTimeout(_timeoutID);
initM(_tm, _sid, _o);
```

Unfortunately `change_type_order()` which is called in `updateSelect()` does not refresh monitoring list if order remains the same...

**Comment by lpinsivy** [comment]
The Centreon web 2.8.28 has been released

**Comment by CPbN** [comment]
@lpinsivy I did not test 19.05.0 yet, but issue was still present in 19.04.0...

**Comment by CPbN** [comment]
Also fixed in 19.04.1 :+1:  Thx !

**Comment by ptitpopey** [comment]
Issue #7306 not resolved. I have upgrade to 2.8.28 and the problem appear again.

**Comment by ptitpopey** [comment]
Please re-open this issue

**Comment by CPbN** [comment]
Sounds like required modifications have been done here https://github.com/centreon/centreon/commit/1fa64fd613beb5dee00efa934b778ecc305ad198 in service.php, in 19.04.1.
But they are not in 2.8.28.
My 2 cents, why don't you upgrade to 19.04.1 ? :)

**Comment by ptitpopey** [comment]
Why don't you upgrade to 19.04.1 ? :) Not possible for the moment
