### ISSUE TITLE
reports 100% undetermined after upgrade from 19.10 to 20.04

### ISSUE THREAD

**Issue by tobiasschon** [centreon/centreon#8966]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

[root@centreon centreon]# rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-20.04.4-6.el7.centos.noarch
centreon-auto-discovery-server-20.04.4-3.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-broker-20.04.8-1.el7.centos.x86_64
centreon-broker-cbd-20.04.8-1.el7.centos.x86_64
centreon-broker-cbmod-20.04.8-1.el7.centos.x86_64
centreon-broker-core-20.04.8-1.el7.centos.x86_64
centreon-broker-storage-20.04.8-1.el7.centos.x86_64
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-common-20.04.4-6.el7.centos.noarch
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-database-20.04.4-6.el7.centos.noarch
centreon-engine-20.04.6-1.el7.centos.x86_64
centreon-engine-daemon-20.04.6-1.el7.centos.x86_64
centreon-engine-extcommands-20.04.6-1.el7.centos.x86_64
centreon-gorgone-20.04.4-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.4-1.el7.centos.noarch
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-perl-libs-20.04.4-6.el7.centos.noarch
centreon-poller-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-trap-20.04.4-6.el7.centos.noarch
centreon-web-20.04.4-6.el7.centos.noarch
centreon-widget-engine-status-20.04.1-1.el7.centos.noarch
centreon-widget-global-health-20.04.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-grid-map-20.04.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.04.4-4.el7.centos.noarch
centreon-widget-httploader-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.04.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.04.3-3.el7.centos.noarch
centreon-widget-tactical-overview-20.04.0-5.el7.centos.noarch

[root@centreon centreon]# yum history info 66
Loaded plugins: fastestmirror
Transaction ID : 66
Begin time     : Tue Jul  7 11:31:37 2020
Begin rpmdb    : 751:77f6f5e52246de5ed0813612e7df7821ea2db350
End time       :            11:32:35 2020 (58 seconds)
End rpmdb      : 772:094a066e8322001aba202730407e5c14dc101510
User           : root <root>
Return-Code    : Success
Command Line   : update centreon*
Transaction performed with:
    Installed     rpm-4.11.3-43.el7.x86_64                        @base
    Installed     yum-3.4.3-167.el7.centos.noarch                 @base
    Installed     yum-plugin-fastestmirror-1.1.31-54.el7_8.noarch @updates
Packages Altered:
    Dep-Install MariaDB-compat-10.3.22-1.el7.centos.x86_64                          @centreon-stable
    Updated     MariaDB-shared-10.1.38-1.el7.centos.x86_64                          @centreon-stable
    Update                     10.3.22-1.el7.centos.x86_64                          @centreon-stable
    Updated     centreon-19.10.14-5.el7.centos.noarch                               @centreon-stable-noarch
    Update               20.04.4-6.el7.centos.noarch                                @centreon-stable-noarch
    Updated     centreon-auto-discovery-server-19.10.3-1.el7.centos.noarch          @centreon-stable-noarch
    Update                                     20.04.3-3.el7.centos.noarch          @centreon-stable-noarch
    Updated     centreon-base-config-centreon-engine-19.10.14-5.el7.centos.noarch   @centreon-stable-noarch
    Update                                           20.04.4-6.el7.centos.noarch    @centreon-stable-noarch
    Updated     centreon-broker-19.10.4-1.el7.centos.x86_64                         @centreon-stable
    Update                      20.04.6-3.el7.centos.x86_64                         @centreon-stable
    Updated     centreon-broker-cbd-19.10.4-1.el7.centos.x86_64                     @centreon-stable
    Update                          20.04.6-3.el7.centos.x86_64                     @centreon-stable
    Updated     centreon-broker-cbmod-19.10.4-1.el7.centos.x86_64                   @centreon-stable
    Update                            20.04.6-3.el7.centos.x86_64                   @centreon-stable
    Updated     centreon-broker-core-19.10.4-1.el7.centos.x86_64                    @centreon-stable
    Update                           20.04.6-3.el7.centos.x86_64                    @centreon-stable
    Updated     centreon-broker-storage-19.10.4-1.el7.centos.x86_64                 @centreon-stable
    Update                              20.04.6-3.el7.centos.x86_64                 @centreon-stable
    Updated     centreon-clib-19.10.0-6.el7.centos.x86_64                           @centreon-stable
    Update                    20.04.0-7.el7.centos.x86_64                           @centreon-stable
    Updated     centreon-common-19.10.14-5.el7.centos.noarch                        @centreon-stable-noarch
    Update                      20.04.4-6.el7.centos.noarch                         @centreon-stable-noarch
    Updated     centreon-connector-19.10.1-1.el7.centos.x86_64                      @centreon-stable
    Update                         20.04.0-2.el7.centos.x86_64                      @centreon-stable
    Updated     centreon-connector-perl-19.10.1-1.el7.centos.x86_64                 @centreon-stable
    Update                              20.04.0-2.el7.centos.x86_64                 @centreon-stable
    Updated     centreon-connector-ssh-19.10.1-1.el7.centos.x86_64                  @centreon-stable
    Update                             20.04.0-2.el7.centos.x86_64                  @centreon-stable
    Updated     centreon-database-19.10.14-5.el7.centos.noarch                      @centreon-stable-noarch
    Update                        20.04.4-6.el7.centos.noarch                       @centreon-stable-noarch
    Updated     centreon-engine-19.10.14-1.el7.centos.x86_64                        @centreon-stable
    Update                      20.04.4-1.el7.centos.x86_64                         @centreon-stable
    Updated     centreon-engine-daemon-19.10.14-1.el7.centos.x86_64                 @centreon-stable
    Update                             20.04.4-1.el7.centos.x86_64                  @centreon-stable
    Updated     centreon-engine-extcommands-19.10.14-1.el7.centos.x86_64            @centreon-stable
    Update                                  20.04.4-1.el7.centos.x86_64             @centreon-stable
    Dep-Install centreon-gorgone-20.04.3-1.el7.centos.noarch                        @centreon-stable-noarch
    Dep-Install centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch        @centreon-stable-noarch
    Updated     centreon-license-manager-19.10.1-3.el7.centos.noarch                @centreon-stable-noarch
    Update                               20.04.2-1.el7.centos.noarch                @centreon-stable-noarch
    Updated     centreon-license-manager-common-19.10.1-3.el7.centos.noarch         @centreon-stable-noarch
    Update                                      20.04.2-1.el7.centos.noarch         @centreon-stable-noarch
    Updated     centreon-perl-libs-19.10.14-5.el7.centos.noarch                     @centreon-stable-noarch
    Update                         20.04.4-6.el7.centos.noarch                      @centreon-stable-noarch
    Updated     centreon-poller-centreon-engine-19.10.14-5.el7.centos.noarch        @centreon-stable-noarch
    Update                                      20.04.4-6.el7.centos.noarch         @centreon-stable-noarch
    Updated     centreon-pp-manager-19.10.1-3.el7.centos.noarch                     @centreon-stable-noarch
    Update                          20.04.1-1.el7.centos.noarch                     @centreon-stable-noarch
    Updated     centreon-trap-19.10.14-5.el7.centos.noarch                          @centreon-stable-noarch
    Update                    20.04.4-6.el7.centos.noarch                           @centreon-stable-noarch
    Updated     centreon-web-19.10.14-5.el7.centos.noarch                           @centreon-stable-noarch
    Update                   20.04.4-6.el7.centos.noarch                            @centreon-stable-noarch
    Updated     centreon-widget-engine-status-19.10.2-1.el7.centos.noarch           @centreon-stable-noarch
    Update                                    20.04.1-1.el7.centos.noarch           @centreon-stable-noarch
    Updated     centreon-widget-global-health-19.10.1-1.el7.centos.noarch           @centreon-stable-noarch
    Update                                    20.04.0-5.el7.centos.noarch           @centreon-stable-noarch
    Updated     centreon-widget-graph-monitoring-19.10.1-1.el7.centos.noarch        @centreon-stable-noarch
    Update                                       20.04.0-5.el7.centos.noarch        @centreon-stable-noarch
    Updated     centreon-widget-grid-map-19.10.1-1.el7.centos.noarch                @centreon-stable-noarch
    Update                               20.04.0-5.el7.centos.noarch                @centreon-stable-noarch
    Updated     centreon-widget-host-monitoring-19.10.5-2.el7.centos.noarch         @centreon-stable-noarch
    Update                                      20.04.3-2.el7.centos.noarch         @centreon-stable-noarch
    Updated     centreon-widget-hostgroup-monitoring-19.10.1-1.el7.centos.noarch    @centreon-stable-noarch
    Update                                           20.04.0-5.el7.centos.noarch    @centreon-stable-noarch
    Updated     centreon-widget-httploader-19.10.1-1.el7.centos.noarch              @centreon-stable-noarch
    Update                                 20.04.0-5.el7.centos.noarch              @centreon-stable-noarch
    Updated     centreon-widget-live-top10-cpu-usage-19.10.1-1.el7.centos.noarch    @centreon-stable-noarch
    Update                                           20.04.0-5.el7.centos.noarch    @centreon-stable-noarch
    Updated     centreon-widget-live-top10-memory-usage-19.10.1-1.el7.centos.noarch @centreon-stable-noarch
    Update                                              20.04.0-5.el7.centos.noarch @centreon-stable-noarch
    Updated     centreon-widget-service-monitoring-19.10.5-1.el7.centos.noarch      @centreon-stable-noarch
    Update                                         20.04.2-1.el7.centos.noarch      @centreon-stable-noarch
    Updated     centreon-widget-servicegroup-monitoring-19.10.1-1.el7.centos.noarch @centreon-stable-noarch
    Update                                              20.04.0-5.el7.centos.noarch @centreon-stable-noarch
    Updated     centreon-widget-tactical-overview-19.10.1-1.el7.centos.noarch       @centreon-stable-noarch
    Update                                        20.04.0-5.el7.centos.noarch       @centreon-stable-noarch
    Dep-Install perl-Clone-0.34-5.el7.x86_64                                        @base
    Dep-Install perl-Clone-Choose-0.010-1.el7.noarch                                @centreon-stable-noarch
    Dep-Install perl-Crypt-CBC-2.33-2.el7.noarch                                    @base
    Dep-Install perl-CryptX-0.064-1.el7.x86_64                                      @centreon-stable
    Dep-Install perl-Digest-MD5-File-0.08-4.el7.noarch                              @centreon-stable-noarch
    Dep-Install perl-HTTP-Daemon-SSL-1.04-20.el7.noarch                             @centreon-stable-noarch
    Dep-Install perl-Hash-Merge-0.300-1.el7.noarch                                  @centreon-stable-noarch
    Dep-Install perl-JSON-PP-2.27202-2.el7.noarch                                   @base
    Dep-Install perl-JSON-XS-1:3.01-2.el7.x86_64                                    @centreon-stable
    Dep-Install perl-Net-Curl-0.39-1.el7.centos.x86_64                              @centreon-stable
    Dep-Install perl-NetAddr-IP-4.069-3.el7.x86_64                                  @base
    Dep-Install perl-Schedule-Cron-1.01-1.el7.noarch                                @centreon-stable-noarch
    Dep-Install perl-Time-ParseDate-2015.103-1.el7.noarch                           @centreon-stable-noarch
    Dep-Install perl-Types-Serialiser-1.0-1.el7.centos.noarch                       @centreon-stable-noarch
    Dep-Install perl-UUID-0.04-1.el7.centos.x86_64                                  @centreon-stable
    Dep-Install perl-YAML-0.84-5.el7.noarch                                         @base
    Dep-Install perl-YAML-LibYAML-0.80-1.el7.x86_64                                 @centreon-stable
    Dep-Install perl-common-sense-3.74-1.el7.centos.noarch                          @centreon-stable-noarch
Scriptlet output:
   1 /usr/bin/chmod: cannot access ‘/var/lib/centreon-gorgone/.ssh/id_rsa’: No such file or directory
   2 warning: %post(centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch) scriptlet failed, exit status 1
   3 warning: file /usr/share/centreon/www/install/sql/centreon/Update-DB-19.10.4.sql: remove failed: No such file or directory
   4 warning: file /usr/share/centreon/www/install/sql/centreon/Update-DB-19.10.14.sql: remove failed: No such file or directory
   5 warning: file /usr/share/centreon/www/install/php/Update-19.10.9.php: remove failed: No such file or directory
   6 warning: file /usr/share/centreon/www/install/php/Update-19.10.8.php: remove failed: No such file or directory
   7 warning: file /usr/share/centreon/www/install/php/Update-19.10.7.php: remove failed: No such file or directory
   8 warning: file /usr/share/centreon/www/install/php/Update-19.10.6.php: remove failed: No such file or directory
   9 warning: file /usr/share/centreon/www/install/php/Update-19.10.5.php: remove failed: No such file or directory
  10 warning: file /usr/share/centreon/www/install/php/Update-19.10.4.php: remove failed: No such file or directory
  11 warning: file /usr/share/centreon/www/install/php/Update-19.10.14.php: remove failed: No such file or directory
  12 warning: file /usr/share/centreon/www/install/php/Update-19.10.13.php: remove failed: No such file or directory
  13 warning: file /usr/share/centreon/www/install/php/Update-19.10.12.php: remove failed: No such file or directory
  14 warning: file /usr/share/centreon/www/install/php/Update-19.10.11.php: remove failed: No such file or directory
  15 warning: file /usr/share/centreon/www/install/php/Update-19.10.10.php: remove failed: No such file or directory
  16 warning: file /usr/share/centreon/www/install/RELEASENOTES.html: remove failed: No such file or directory
  17 Failed to try-restart centcore.service: Unit not found.
  18 warning: /etc/centreon-broker/watchdog.xml saved as /etc/centreon-broker/watchdog.xml.rpmsave
  19 warning: /etc/centreon-broker/central-rrd.xml saved as /etc/centreon-broker/central-rrd.xml.rpmsave
  20 warning: /etc/centreon-broker/central-broker.xml saved as /etc/centreon-broker/central-broker.xml.rpmsave

***Operating System***

CentOS

***Browser used***

- [x] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***
Virtual Machine ontop of Vmware ESXi 6.0

### Description

Reports are showing 35-100% undetermined on the reports since we upgraded from 19.10 to 20.04

Steps taken to solve the issue by our own:
Have done a downgrade or else the commands below doesnt work at all. 
Duplicate warnings in the database.

[root@centreon reporting]# centreon -v
Centreon version 20.04.5 - Copyright Centreon - www.centreon.com

/usr/share/centreon/cron/dashboardBuilder --config=/etc/centreon/conf.pm -r
/usr/share/centreon/cron/eventReportBuilder --config=/etc/centreon/conf.pm -r

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I login to Centreon
2. I go to dashboard -> service group
3. Choosing the service-group i want to get reports from
4. Choosing last month
5. reports end up with 35-100% undetermined results
6  Chosing last year shows 100% undetermined results

### Describe the received result
Reports show very unexpected numbers.

### Describe the expected result
Numbers that are not showing undetermined results.

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
[root@centreon centreon]# tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 208
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 209
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 206
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 207
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 208
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 209
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 206
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 207
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 208
[07-Sep-2020 16:35:03 Europe/Paris] PHP Warning:  Division by zero in /usr/share/centreon/www/include/reporting/dashboard/csvExport/csv_ServiceLogs.php on line 209

```
**centreon-engine logs (*if needed*)**

```
[root@centreon centreon]# tail -f /var/log/centreon-engine/centengine.log
[1599545325] [30671] SERVICE ALERT: mwse1594;Windows SNMP MEM;OK;HARD;1;OK: Ram Total: 63.84GB Used: 21.15GB (33.13%) Free: 42.69GB (66.87%)
[1599545330] [30671] SERVICE ALERT: bygg-5;checkcpu;CRITICAL;HARD;3;CRITICAL: 1m: 100%, 5s: 100%
[1599545505] [30671] SERVICE ALERT: mwse1594;Windows SNMP MEM;UNKNOWN;SOFT;1;UNKNOWN: SNMP Table Request : Timeout
[1599545505] [30671] SERVICE ALERT: mwse1594;Windows SNMP CPU;UNKNOWN;SOFT;1;UNKNOWN: SNMP Table Request : Timeout
[1599545565] [30671] SERVICE ALERT: mwse1594;Windows SNMP CPU;OK;SOFT;2;OK: 12 CPU(s) average usage is 51.33 %
[1599545570] [30671] SERVICE ALERT: mwse1594;Windows SNMP MEM;OK;SOFT;2;OK: Ram Total: 63.84GB Used: 22.11GB (34.63%) Free: 41.73GB (65.37%)
[1599545620] [30671] SERVICE ALERT: smon211;checkmem;OK;HARD;1;OK: physical: Total: 20GB - Used: 18.947GB (94%) - Free: 1.052GB (5%)
[1599545620] [30671] SERVICE ALERT: mwse1594;Windows SNMP CPU;OK;HARD;1;OK: 12 CPU(s) average usage is 88.25 %
[1599545625] [30671] SERVICE ALERT: mwse1594;Windows SNMP MEM;OK;HARD;1;OK: Ram Total: 63.84GB Used: 21.21GB (33.23%) Free: 42.62GB (66.77%)
[1599545630] [30671] SERVICE ALERT: bygg-5;checkcpu;OK;HARD;1;OK: CPU load is ok.

tail -f /var/log/centreon-engine/centengine.log

**centreon gorgone logs for Centreon >= 20.4  (*if needed*)**

```
tail -f /var/log/centreon-gorgone/gorgoned.log
[root@centreon centreon]# tail -f /var/log/centreon-gorgone/gorgoned.log
2020-09-08 08:14:05 - INFO - [proxy] Received setlogs for '4'
2020-09-08 08:14:05 - INFO - [proxy] Pong received from '4'
2020-09-08 08:15:00 - INFO - [cron] Launching job 'broker_stats'
2020-09-08 08:15:00 - INFO - [cron] Launching job 'engine_stats'
2020-09-08 08:15:00 - INFO - [statistics] Collecting Engine statistics from target '4'
2020-09-08 08:15:00 - INFO - [statistics] Collecting Engine statistics from target '1'
2020-09-08 08:15:03 - INFO - [proxy] Received setlogs for '4'
2020-09-08 08:15:19 - INFO - [proxy] Send pings
2020-09-08 08:15:20 - INFO - [proxy] Received setlogs for '4'
2020-09-08 08:15:20 - INFO - [proxy] Pong received from '4'
^C

The cronjob that is configured does run, but the reports are still undetermined.
With the newest available version this program gives this error therefore the downgrade.
 cat /var/log/centreon/dashboardBuilder.log
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonService.pm line 77.
2020-09-07 10:13:56 - ERROR - MySQL error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '344,0,0,0,0,0,86400,0,0,0,0,1599343200,1599429600),(63,177,86400,0,0,0,0,0,0,0,0' at line 1 (caller: centreon::reporting::CentreonDashboard:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonDashboard.pm:161)

All data from before we upgraded are obsolete.

![undetermined](https://user-images.githubusercontent.com/70902287/92442122-a64f3100-f1af-11ea-9c18-48111051d58b.png)
![last month undetermined](https://user-images.githubusercontent.com/70902287/92442212-c7b01d00-f1af-11ea-998f-4302fd92c47d.png)

**Comment by lpinsivy** [comment]
Hi @tobiasschon ,

Which DBMS and version do you used?

Regards,

**Comment by tobiasschon** [comment]
Hi!
Kriko has been connected to our environment and filed a bug in your IBT i think with the same issue.
We are using the latest mariadb 10.3 stable version. 
https://downloads.mariadb.org/mariadb/10.3.24/
I can post more exact tomorrow morning.

**Comment by tobiasschon** [comment]
Hi,

i doublechecked this one and we are using 

[root@centreon ~]# rpm -qa | grep MariaDB
MariaDB-client-10.3.22-1.el7.centos.x86_64
MariaDB-server-10.3.22-1.el7.centos.x86_64
MariaDB-compat-10.3.22-1.el7.centos.x86_64
MariaDB-shared-10.3.22-1.el7.centos.x86_64
MariaDB-common-10.3.22-1.el7.centos.x86_64
[root@centreon ~]#

**Comment by tobiasschon** [comment]
@lpinsivy Do you have any kind of information to share?

**Comment by lpinsivy** [comment]
@tobiasschon can you give me the result of the following SQL request:

`SELECT * FROM log_archive_service WHERE host_id = '558' AND service_id = '7479' AND date_start >= '1585692000' AND date_end < '1588284000'`

Replace host_id = '558' AND service_id = '7479' by the ID of a service in your Prio1 servicegroup.

**Comment by tobiasschon** [comment]
hmm, actually, i now moved all my service by hostgroups to service by host.
So i'm not sure if i can replicate the issue in my environment.
But my reports are not building correctly.
I got the tip from kriko, he told me he had created a internal bug for you with some information about this issue.
I think he could replicate it very easily aswell.

**Comment by tobiasschon** [comment]
here's an output of the command above :)
Is this good or bad news?
`MariaDB [centreon_storage]> SELECT * FROM log_archive_service WHERE host_id = '38' AND service_id = '602' AND date_start >= '1585692000' AND date_end < '1588284000';
+--------+---------+------------+-----------------+-----------+----------------------+----------------+----------------------+----------------+-----------------------+-----------------+---------------------------+-----------------+------------+------------+
| log_id | host_id | service_id | OKTimeScheduled | OKnbEvent | WARNINGTimeScheduled | WARNINGnbEvent | UNKNOWNTimeScheduled | UNKNOWNnbEvent | CRITICALTimeScheduled | CRITICALnbEvent | UNDETERMINEDTimeScheduled | MaintenanceTime | date_start | date_end   |
+--------+---------+------------+-----------------+-----------+----------------------+----------------+----------------------+----------------+-----------------------+-----------------+---------------------------+-----------------+------------+------------+
| 841999 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1585692000 | 1585778400 |
| 842704 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1585778400 | 1585864800 |
| 843409 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1585864800 | 1585951200 |
| 844114 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1585951200 | 1586037600 |
| 844819 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586037600 | 1586124000 |
| 845524 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586124000 | 1586210400 |
| 846229 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586210400 | 1586296800 |
| 846934 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586296800 | 1586383200 |
| 847639 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586383200 | 1586469600 |
| 848344 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586469600 | 1586556000 |
| 849049 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586556000 | 1586642400 |
| 849754 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586642400 | 1586728800 |
| 850459 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586728800 | 1586815200 |
| 851164 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586815200 | 1586901600 |
| 851869 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586901600 | 1586988000 |
| 852574 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1586988000 | 1587074400 |
| 853279 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587074400 | 1587160800 |
| 853984 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587160800 | 1587247200 |
| 854689 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587247200 | 1587333600 |
| 855394 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587333600 | 1587420000 |
| 856099 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587420000 | 1587506400 |
| 856804 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587506400 | 1587592800 |
| 857509 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587592800 | 1587679200 |
| 858214 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587679200 | 1587765600 |
| 858919 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587765600 | 1587852000 |
| 859624 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587852000 | 1587938400 |
| 860329 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1587938400 | 1588024800 |
| 861034 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1588024800 | 1588111200 |
| 861739 |      38 |        602 |               0 |         0 |                    0 |              0 |                    0 |              0 |                     0 |               0 |                     86400 |               0 | 1588111200 | 1588197600 |
+--------+---------+------------+-----------------+-----------+----------------------+----------------+----------------------+----------------+-----------------------+-----------------+---------------------------+-----------------+------------+------------+
29 rows in set (0.035 sec)

MariaDB [centreon_storage]>
`

**Comment by tobiasschon** [comment]
`2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '150-1042-1600815996' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (150, 1042, 3, 1600815996, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '24-510-1600815716' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (24, 510, 1, 1600815716, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '27-801-1600853854' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (27, 801, 0, 1600853854, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '27-369-1600853834' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (27, 369, 0, 1600853834, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '123-913-1600868734' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (123, 913, 0, 1600868734, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '43-414-1600816598' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (43, 414, 0, 1600816598, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - ERROR - MySQL error: Duplicate entry '39-479-1600815656' for key 'host_id' (caller: centreon::reporting::CentreonServiceStateEvents:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm:237)
Query: INSERT INTO `servicestateevents` (`host_id`, `service_id`, `state`, `start_time`, `end_time`, `last_update`, `in_downtime`, `ack_time`, `in_ack`) VALUES (39, 479, 2, 1600815656, 1600898400, 1, 0, NULL, '0')

2020-09-24 03:00:03 - INFO - Exiting program...
[root@centreon centreon]#
`

When the script is running without the rebuild flag (-r) it's getting reports of duplicate entries.

**Comment by vhsantos** [comment]
Hello Masters, 

I have the same problem.. in my case, the problem started with the last upgrade.

![centreon-undertemined](https://user-images.githubusercontent.com/1770630/94807633-37e94180-03f0-11eb-88dc-fbdc26ec3cc7.png)

My logs and when I try to use the command 
`su - centreon -c "/usr/share/centreon/cron/dashboardBuilder --config=/etc/centreon/conf.pm"`

I get this error:

`2020-09-26 06:00:01 - INFO - Processing period: Fri Sep 25 00:00:00 2020 => Sat Sep 26 00:00:00 2020
2020-09-26 06:00:01 - ERROR - MySQL error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1303,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(141,1367,86400,0,0,0,0,0,0,' at line 1 (caller: centreon::reporting::CentreonDashboard:/usr/share/perl5/vendor_perl/centreon/reporting/CentreonDashboard.pm:161)
Query: INSERT INTO `log_archive_service` (`host_id`, `service_id`, `OKTimeScheduled`, `WARNINGTimeScheduled`, `CRITICALTimeScheduled`, `UNKNOWNTimeScheduled`, `MaintenanceTime`, `UNDETERMINEDTimeScheduled`, `OKnbEvent`, `WARNINGnbEvent`, `CRITICALnbEvent`, `UNKNOWNnbEvent`, `date_start`, `date_end`) VALUES (57,1177,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(104,587,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(67,331,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(104,593,0,0,86400,0,0,0,0,0,1,0,1601002800,1601089200),(125,1040,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(78,610,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(78,607,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(82,631,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(135,1313,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(31,659,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(141,1378,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(122,508,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(75,1259,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(84,707,81900,0,0,0,4500,0,7,0,0,0,1601002800,1601089200),(127,817,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(125,792,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(36,474,0,0,0,0,0,86400,0,0,0,0,1601002800,1601089200),(90,1473,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200),(72,684,86400,0,0,0,0,0,0,0,0,0,1601002800,1601089200) [....]`

bellow, the list of last updates:

> Sep 03 08:29:18 Updated: 1:grub2-common-2.02-0.86.el7.centos.noarch
> Sep 03 08:29:18 Updated: 1:grub2-tools-minimal-2.02-0.86.el7.centos.x86_64
> Sep 03 08:29:18 Updated: systemd-libs-219-73.el7_8.9.x86_64
> Sep 03 08:29:19 Updated: 1:grub2-tools-2.02-0.86.el7.centos.x86_64
> Sep 03 08:29:19 Updated: libcurl-7.29.0-57.el7_8.1.x86_64
> Sep 03 08:29:19 Updated: curl-7.29.0-57.el7_8.1.x86_64
> Sep 03 08:29:19 Updated: 1:grub2-tools-extra-2.02-0.86.el7.centos.x86_64
> Sep 03 08:29:20 Updated: 1:dbus-libs-1.10.24-14.el7_8.x86_64
> Sep 03 08:29:23 Updated: systemd-219-73.el7_8.9.x86_64
> Sep 03 08:29:23 Updated: 1:dbus-1.10.24-14.el7_8.x86_64
> Sep 03 08:29:23 Updated: centreon-common-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:23 Updated: centreon-perl-libs-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:31 Updated: centreon-web-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:31 Updated: centreon-broker-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:31 Updated: centreon-broker-storage-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:31 Updated: centreon-broker-core-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:32 Updated: centreon-engine-daemon-20.04.6-1.el7.centos.x86_64
> Sep 03 08:29:32 Updated: centreon-engine-extcommands-20.04.6-1.el7.centos.x86_64
> Sep 03 08:29:32 Updated: centreon-engine-20.04.6-1.el7.centos.x86_64
> Sep 03 08:29:33 Updated: centreon-broker-cbmod-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:33 Updated: centreon-broker-cbd-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:34 Updated: centreon-widget-host-monitoring-20.04.4-4.el7.centos.noarch
> Sep 03 08:29:34 Updated: centreon-widget-service-monitoring-20.04.3-3.el7.centos.noarch
> Sep 03 08:29:34 Updated: centreon-trap-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:34 Updated: 1:grub2-pc-modules-2.02-0.86.el7.centos.noarch
> Sep 03 08:29:34 Updated: 1:grub2-pc-2.02-0.86.el7.centos.x86_64
> Sep 03 08:29:35 Updated: centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200803-072952.el7.centos.noarch
> Sep 03 08:29:35 Installed: bzip2-1.0.6-13.el7.x86_64
> Sep 03 08:29:35 Updated: centreon-gorgone-20.04.4-1.el7.centos.noarch
> Sep 03 08:29:35 Updated: centreon-gorgone-centreon-config-20.04.4-1.el7.centos.noarch
> Sep 03 08:29:35 Updated: centreon-auto-discovery-server-20.04.4-3.el7.centos.noarch
> Sep 03 08:29:37 Updated: kernel-tools-libs-3.10.0-1127.19.1.el7.x86_64
> Sep 03 08:29:37 Updated: centreon-plugin-Hardware-Printers-Generic-Snmp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Monitoring-Centreon-Database-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-database-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Protocol-Ldap-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Protocol-Http-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Operatingsystems-Linux-Snmp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Databases-Mysql-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Operatingsystems-Windows-Snmp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Monitoring-Centreon-Central-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Network-Cisco-Standard-Snmp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Monitoring-Centreon-Poller-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Protocol-Dns-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-plugin-Applications-Protocol-Ftp-20200803-072952.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-poller-centreon-engine-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-base-config-centreon-engine-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:37 Updated: centreon-20.04.5-5.el7.centos.noarch
> Sep 03 08:29:38 Updated: kernel-tools-3.10.0-1127.19.1.el7.x86_64
> Sep 03 08:29:38 Updated: 1:grub2-2.02-0.86.el7.centos.x86_64
> Sep 03 08:29:38 Updated: centreon-broker-graphite-20.04.8-1.el7.centos.x86_64
> Sep 03 08:29:38 Updated: systemd-sysv-219-73.el7_8.9.x86_64
> Sep 03 08:29:51 Installed: kernel-3.10.0-1127.19.1.el7.x86_64
> Sep 03 08:29:51 Updated: python-perf-3.10.0-1127.19.1.el7.x86_64
> Sep 03 08:29:52 Updated: kernel-headers-3.10.0-1127.19.1.el7.x86_64
> Sep 03 08:29:52 Updated: httpd24-libnghttp2-1.7.1-8.el7.1.x86_64



before 02/Sep all dashboards reports worked fine.

**Comment by vhsantos** [comment]
More details about the update:

> # yum history info  38
> Loaded plugins: fastestmirror
> Transaction ID : 38
> Begin time     : Thu Sep  3 08:29:16 2020
> Begin rpmdb    : 832:d1cba4b738dea9e544d5d1aad06862dbf759c577
> End time       :            08:31:55 2020 (159 seconds)
> End rpmdb      : 833:e6c9e81f6d988431d9b2bf9d11e8a96886b37b9f
> User           : root <root>
> Return-Code    : Success
> Command Line   : update
> Transaction performed with:
>     Installed     rpm-4.11.3-43.el7.x86_64                        @base
>     Installed     yum-3.4.3-167.el7.centos.noarch                 @base
>     Installed     yum-plugin-fastestmirror-1.1.31-54.el7_8.noarch @updates
> Packages Altered:
>     Dep-Install bzip2-1.0.6-13.el7.x86_64                                                                   @base
>     Updated     centreon-20.04.4-6.el7.centos.noarch                                                        @centreon-stable-noarch
>     Update               20.04.5-5.el7.centos.noarch                                                        @centreon-stable-noarch
>     Updated     centreon-auto-discovery-server-20.04.3-3.el7.centos.noarch                                  @centreon-stable-noarch
>     Update                                     20.04.4-3.el7.centos.noarch                                  @centreon-stable-noarch
>     Updated     centreon-base-config-centreon-engine-20.04.4-6.el7.centos.noarch                            @centreon-stable-noarch
>     Update                                           20.04.5-5.el7.centos.noarch                            @centreon-stable-noarch
>     Updated     centreon-broker-20.04.6-3.el7.centos.x86_64                                                 @centreon-stable
>     Update                      20.04.8-1.el7.centos.x86_64                                                 @centreon-stable
>     Updated     centreon-broker-cbd-20.04.6-3.el7.centos.x86_64                                             @centreon-stable
>     Update                          20.04.8-1.el7.centos.x86_64                                             @centreon-stable
>     Updated     centreon-broker-cbmod-20.04.6-3.el7.centos.x86_64                                           @centreon-stable
>     Update                            20.04.8-1.el7.centos.x86_64                                           @centreon-stable
>     Updated     centreon-broker-core-20.04.6-3.el7.centos.x86_64                                            @centreon-stable
>     Update                           20.04.8-1.el7.centos.x86_64                                            @centreon-stable
>     Updated     centreon-broker-graphite-20.04.6-3.el7.centos.x86_64                                        @centreon-stable
>     Update                               20.04.8-1.el7.centos.x86_64                                        @centreon-stable
>     Updated     centreon-broker-storage-20.04.6-3.el7.centos.x86_64                                         @centreon-stable
>     Update                              20.04.8-1.el7.centos.x86_64                                         @centreon-stable
>     Updated     centreon-common-20.04.4-6.el7.centos.noarch                                                 @centreon-stable-noarch
>     Update                      20.04.5-5.el7.centos.noarch                                                 @centreon-stable-noarch
>     Updated     centreon-database-20.04.4-6.el7.centos.noarch                                               @centreon-stable-noarch
>     Update                        20.04.5-5.el7.centos.noarch                                               @centreon-stable-noarch
>     Updated     centreon-engine-20.04.4-1.el7.centos.x86_64                                                 @centreon-stable
>     Update                      20.04.6-1.el7.centos.x86_64                                                 @centreon-stable
>     Updated     centreon-engine-daemon-20.04.4-1.el7.centos.x86_64                                          @centreon-stable
>     Update                             20.04.6-1.el7.centos.x86_64                                          @centreon-stable
>     Updated     centreon-engine-extcommands-20.04.4-1.el7.centos.x86_64                                     @centreon-stable
>     Update                                  20.04.6-1.el7.centos.x86_64                                     @centreon-stable
>     Updated     centreon-gorgone-20.04.3-1.el7.centos.noarch                                                @centreon-stable-noarch
>     Update                       20.04.4-1.el7.centos.noarch                                                @centreon-stable-noarch
>     Updated     centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch                                @centreon-stable-noarch
>     Update                                       20.04.4-1.el7.centos.noarch                                @centreon-stable-noarch
>     Updated     centreon-perl-libs-20.04.4-6.el7.centos.noarch                                              @centreon-stable-noarch
>     Update                         20.04.5-5.el7.centos.noarch                                              @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Databases-Mysql-20200602-094050.el7.centos.noarch              @centreon-stable-noarch
>     Update                                                   20200803-072952.el7.centos.noarch              @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Monitoring-Centreon-Central-20200602-094050.el7.centos.noarch  @centreon-stable-noarch
>     Update                                                               20200803-072952.el7.centos.noarch  @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Monitoring-Centreon-Database-20200602-094050.el7.centos.noarch @centreon-stable-noarch
>     Update                                                                20200803-072952.el7.centos.noarch @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200602-094050.el7.centos.noarch @centreon-stable-noarch
>     Update                                                                20200803-072952.el7.centos.noarch @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Monitoring-Centreon-Poller-20200602-094050.el7.centos.noarch   @centreon-stable-noarch
>     Update                                                              20200803-072952.el7.centos.noarch   @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Protocol-Dns-20200602-094050.el7.centos.noarch                 @centreon-stable-noarch
>     Update                                                20200803-072952.el7.centos.noarch                 @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Protocol-Ftp-20200602-094050.el7.centos.noarch                 @centreon-stable-noarch
>     Update                                                20200803-072952.el7.centos.noarch                 @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Protocol-Http-20200602-094050.el7.centos.noarch                @centreon-stable-noarch
>     Update                                                 20200803-072952.el7.centos.noarch                @centreon-stable-noarch
>     Updated     centreon-plugin-Applications-Protocol-Ldap-20200602-094050.el7.centos.noarch                @centreon-stable-noarch
>     Update                                                 20200803-072952.el7.centos.noarch                @centreon-stable-noarch
>     Updated     centreon-plugin-Hardware-Printers-Generic-Snmp-20200602-094050.el7.centos.noarch            @centreon-stable-noarch
>     Update                                                     20200803-072952.el7.centos.noarch            @centreon-stable-noarch
>     Updated     centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200602-094050.el7.centos.noarch        @centreon-stable-noarch
>     Update                                                         20200803-072952.el7.centos.noarch        @centreon-stable-noarch
>     Updated     centreon-plugin-Network-Cisco-Standard-Snmp-20200602-094050.el7.centos.noarch               @centreon-stable-noarch
>     Update                                                  20200803-072952.el7.centos.noarch               @centreon-stable-noarch
>     Updated     centreon-plugin-Operatingsystems-Linux-Snmp-20200602-094050.el7.centos.noarch               @centreon-stable-noarch
>     Update                                                  20200803-072952.el7.centos.noarch               @centreon-stable-noarch
>     Updated     centreon-plugin-Operatingsystems-Windows-Snmp-20200602-094050.el7.centos.noarch             @centreon-stable-noarch
>     Update                                                    20200803-072952.el7.centos.noarch             @centreon-stable-noarch
>     Updated     centreon-poller-centreon-engine-20.04.4-6.el7.centos.noarch                                 @centreon-stable-noarch
>     Update                                      20.04.5-5.el7.centos.noarch                                 @centreon-stable-noarch
>     Updated     centreon-trap-20.04.4-6.el7.centos.noarch                                                   @centreon-stable-noarch
>     Update                    20.04.5-5.el7.centos.noarch                                                   @centreon-stable-noarch
>     Updated     centreon-web-20.04.4-6.el7.centos.noarch                                                    @centreon-stable-noarch
>     Update                   20.04.5-5.el7.centos.noarch                                                    @centreon-stable-noarch
>     Updated     centreon-widget-host-monitoring-20.04.3-2.el7.centos.noarch                                 @centreon-stable-noarch
>     Update                                      20.04.4-4.el7.centos.noarch                                 @centreon-stable-noarch
>     Updated     centreon-widget-service-monitoring-20.04.2-1.el7.centos.noarch                              @centreon-stable-noarch
>     Update                                         20.04.3-3.el7.centos.noarch                              @centreon-stable-noarch
>     Updated     curl-7.29.0-57.el7.x86_64                                                                   @base
>     Update           7.29.0-57.el7_8.1.x86_64                                                               @updates
>     Updated     dbus-1:1.10.24-13.el7_6.x86_64                                                              @updates
>     Update           1:1.10.24-14.el7_8.x86_64                                                              @updates
>     Updated     dbus-libs-1:1.10.24-13.el7_6.x86_64                                                         @updates
>     Update                1:1.10.24-14.el7_8.x86_64                                                         @updates
>     Updated     grub2-1:2.02-0.81.el7.centos.x86_64                                                         @base
>     Update            1:2.02-0.86.el7.centos.x86_64                                                         @updates
>     Updated     grub2-common-1:2.02-0.81.el7.centos.noarch                                                  @base
>     Update                   1:2.02-0.86.el7.centos.noarch                                                  @updates
>     Updated     grub2-pc-1:2.02-0.81.el7.centos.x86_64                                                      @base
>     Update               1:2.02-0.86.el7.centos.x86_64                                                      @updates
>     Updated     grub2-pc-modules-1:2.02-0.81.el7.centos.noarch                                              @base
>     Update                       1:2.02-0.86.el7.centos.noarch                                              @updates
>     Updated     grub2-tools-1:2.02-0.81.el7.centos.x86_64                                                   @base
>     Update                  1:2.02-0.86.el7.centos.x86_64                                                   @updates
>     Updated     grub2-tools-extra-1:2.02-0.81.el7.centos.x86_64                                             @base
>     Update                        1:2.02-0.86.el7.centos.x86_64                                             @updates
>     Updated     grub2-tools-minimal-1:2.02-0.81.el7.centos.x86_64                                           @base
>     Update                          1:2.02-0.86.el7.centos.x86_64                                           @updates
>     Updated     httpd24-libnghttp2-1.7.1-8.el7.x86_64                                                       @centos-sclo-rh
>     Update                         1.7.1-8.el7.1.x86_64                                                     @centos-sclo-rh
>     Erase       kernel-3.10.0-1062.9.1.el7.x86_64                                                           @updates
>     Install     kernel-3.10.0-1127.19.1.el7.x86_64                                                          @updates
>     Updated     kernel-headers-3.10.0-1127.13.1.el7.x86_64                                                  @updates
>     Update                     3.10.0-1127.19.1.el7.x86_64                                                  @updates
>     Updated     kernel-tools-3.10.0-1127.13.1.el7.x86_64                                                    @updates
>     Update                   3.10.0-1127.19.1.el7.x86_64                                                    @updates
>     Updated     kernel-tools-libs-3.10.0-1127.13.1.el7.x86_64                                               @updates
>     Update                        3.10.0-1127.19.1.el7.x86_64                                               @updates
>     Updated     libcurl-7.29.0-57.el7.x86_64                                                                @base
>     Update              7.29.0-57.el7_8.1.x86_64                                                            @updates
>     Updated     python-perf-3.10.0-1127.13.1.el7.x86_64                                                     @updates
>     Update                  3.10.0-1127.19.1.el7.x86_64                                                     @updates
>     Updated     systemd-219-73.el7_8.8.x86_64                                                               @updates
>     Update              219-73.el7_8.9.x86_64                                                               @updates
>     Updated     systemd-libs-219-73.el7_8.8.x86_64                                                          @updates
>     Update                   219-73.el7_8.9.x86_64                                                          @updates
>     Updated     systemd-sysv-219-73.el7_8.8.x86_64                                                          @updates
>     Update                   219-73.el7_8.9.x86_64                                                          @updates
> history info
>

**Comment by tobiasschon** [comment]
I managed to rebuild the logs database-table in centreon_storage, and let eventreportbuilder rebuild the data.
There's a program loganalyserbroker that i used to import the data.
Currently there's a bug in the program that doesnt make it compat with strict mode of mariadb.
The change will be put in  PR.

**Comment by vhsantos** [comment]
Hi, any news about this ??

**Comment by saharawolf** [comment]
Hi, 

I got the same issue even with latest version 20.04.5. All reports are showing undetermined and data is not accurate.
Is there any solution to this please ?

Regards

**Comment by teobaldo12** [comment]
Hi, same issue with latest version 20.04.5 + MariaDB 10.3.22-1.el7
any solution ?

Regards

**Comment by tobiasschon** [comment]
do not run the rebuild command of eventreportbuilder and dashboardbuilder. it's gonna truncate your database table 'logs' which gonna force you to reload the databasetable with the help of loganalyzer tool. Which right now contains of a bug

I will write a short workaround of how to solve the issue.

**Comment by kendall-link** [comment]
> I will write a short workaround of how to solve the issue.

Following... We use this feature to provide uptime reports on various services.

**Comment by tobiasschon** [comment]
Go to:
![image](https://user-images.githubusercontent.com/70902287/95953493-29405880-0dfa-11eb-8437-53c782adb483.png)
Change the retention temporarily to 365
![image](https://user-images.githubusercontent.com/70902287/95953539-3bba9200-0dfa-11eb-85fb-a8f0cbf0d25d.png)
check for files here.
![image](https://user-images.githubusercontent.com/70902287/95953643-63a9f580-0dfa-11eb-8f97-e94d63318c05.png)
![image](https://user-images.githubusercontent.com/70902287/95953760-981db180-0dfa-11eb-9763-bd93630da4a4.png)
if you have pollers, put the same files from that remoteserver into here:
![image](https://user-images.githubusercontent.com/70902287/95953887-cdc29a80-0dfa-11eb-86b5-7920433e3d35.png)

when this is done, you run on your own risk, loganalyzerbroker.
The bug that i mentioned need to be fixed as well or else the prograrm will not work and it will break and the changes into the database will not be commit and rollback all changes.

![image](https://user-images.githubusercontent.com/70902287/95954062-08c4ce00-0dfb-11eb-848b-0932a9dc36b6.png)

in this codepart in the file:
nano -c /usr/share/perl5/vendor_perl/centreon/script/logAnalyserBroker.pm
You have an empty string that need to be undef instead.
![image](https://user-images.githubusercontent.com/70902287/95954185-33af2200-0dfb-11eb-8e99-db77076b3aa4.png)

Take a look in your file and you will see the difference.
The program will purge the logs table and import the data based on the logfiles.

I hope this will help users experiencing the same issue as me, running the rebuild parameter and truncated the data to only 31days back.

Follow this guide on your own risk! i will not take responsibility if you have any other kind of issues.
I had to do this procedure to import my data again into the database.

Best way to test is to setup a centreon-lab environment. this is what i did before i ran it on the real machine.
You can do that by restoring the database into a newly installed environment.

mysqldump -u root -p<yourpassword> centreon > centreon-$(date +%Y%m%d).sql
mysqldump -u root --p<yourpassword> centreon_storage > centreon_storage-$(date +%Y%m%d).sql
mysqldump -u root -p<yourpassword> --no-data centreon_storage data_bin >> centreon_storage-$(date +%Y%m%d).sql

**Comment by vhsantos** [comment]
Hello guy,

today I create time to check this (in 10 days more we will need to generate a report again) and a get the bug in my case:

my error was:

`ERROR - MySQL error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1303,0,0,0,0,0,86400,0,0,0,0,1603076400,1603162800), (125,1040,86400,0,0,0,0,0,0,0,0,0,1603076400,1603162800) ... blah .. blah .. blah
`

Starting to understand this query, I got that Centreon have a INSERT like this:

`INSERT INTO `log_archive_service` (`host_id`, `service_id`, `OKTimeScheduled`, `WARNINGTimeScheduled`, `CRITICALTimeScheduled`, `UNKNOWNTimeScheduled`, `MaintenanceTime`, `UNDETERMINEDTimeScheduled`, `OKnbEvent`, `WARNINGnbEvent`, `CRITICALnbEvent`, `UNKNOWNnbEvent`, `date_start`, `date_end`)`

at **/usr/share/perl5/vendor_perl/centreon/script/dashboardBuilder.pm** that will insert the values from this SELECT

```
 66     # getting services linked to hosts
 67     my $query = "SELECT host_host_id as host_id, service_id" .
 68                 " FROM service, host_service_relation" .
 69                 " WHERE service_service_id = service_id" .
 70                 " AND service_register = '1'";
 71     if ($activated == 1) {
 72         $query .= " AND `service_activate`='1'";
 73     }
```
from **/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm**. 

Running this query in the database, I get a row with a null host  (filtered by my service with problem 1303):

```
MariaDB [centreon]> SELECT host_host_id as host_id, service_id FROM service, host_service_relation WHERE service_service_id = service_id AND hostgroup_hg_id IS NOT NULL  AND service_register = '1';
+---------+------------+
| host_id | service_id |
+---------+------------+
|    NULL |       1303 |
+---------+------------+
1 row in set (0.001 sec)
```

So, when centreon try to make the INSERT, they get the error because the **host_id** in the table centreon_storage.log_archive_service can't be **NULL**.

Now, looking about this service (1303 in my case), it is associate with a **host_group** and not a **host** (is the only service that I have to a host group).

So, I made a change in the SELECT to NOT include the services associate with HOSTS Group (line 70 below). After this, I rebuild the dashboard and all the information is OK again.

```
 66     # getting services linked to hosts
 67     my $query = "SELECT host_host_id as host_id, service_id" .
 68                 " FROM service, host_service_relation" .
 69                 " WHERE service_service_id = service_id" .
 70                 " AND hostgroup_hg_id IS NULL " .
 71                 " AND service_register = '1'";
 72     if ($activated == 1) {
 73         $query .= " AND `service_activate`='1'";
 74     }
```

Now the question is: I think that is normal that a service associate with a host group don't have a host_id, in this case the problem is a bug in the code at **/usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm** or Im wrong ?

**Comment by tobiasschon** [comment]
@vhsantos yea we actually migrated all our hostgroups to service by hosts instead of service by hostgroups.

This might have solved alot for us.

**Comment by cgagnaire** [comment]
Hi @tobiasschon and @vhsantos,
This should be fixed by https://github.com/centreon/centreon/pull/9141.
Give it a try if you still use services by hostgroups.

**Comment by vhsantos** [comment]
Thanks @cgagnaire ,

I ca't test it now (end of month), but looking the patch look it will work well.

thanks again.

**Comment by vhsantos** [comment]
Hi @cgagnaire ,

The problem is back after update to 20.10.1
I have tested the patch [9141 ](https://github.com/centreon/centreon/pull/9141) and not work. :-(
Just now, looking to try to find this query and fix it manually again.

**Comment by kendall-link** [comment]
@vhsantos I was wondering if you had any update regarding this?  I've upgraded Centreon and am still experiencing the issue.  I was wondering if I'm alone here or not.

Cheers!

**Comment by vhsantos** [comment]
Hello @kendall-link 

Yes.. I have the same problem after the last upgrade. :-(
I need to replace the file with my changes to exclude this services associate with the hostgroup and recreate the dashboard again.
