### ISSUE TITLE
[20.10.3] - Link NOTEURL on ResourceStatus view open actual page instead of new page

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#9497]
### Feature explanation

On the new "Status Resources" view, the links "NoteURL" open the target in the actual tab instead of the old "Services detailled status" page who open a new tab.

### What is the value of the wanted feature ?

Open a new tab when clicking on the NoteURL link

### Additional information

![image](https://user-images.githubusercontent.com/8720203/108364352-43e66c00-71f6-11eb-9fe2-1b1b0724e9a3.png)

Thanks

**Comment by lpinsivy** [comment]
Hi, Actions and Notes URL have been fixed in Centreon Web 20.10.6 and 21.04.

Regards,

**Comment by cmeschin** [comment]
Hi @lpinsivy 
I'm in 20.10.7 and still present.
The actions note always open link in same page not in new page.
I'm jump of 19.10.22 to 20.10.7.
could it be for that?

Kind regards
